--- #YAML:1.0
name:               Algorithm-Evolutionary-Simple
version:            v0.0.3
abstract:           A few auxiliary functions to run a simple EA in Perl
author:
    - JJ Merelo <jj@merelo.net>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Exporter:        0
    Sort::Key::Top:  0
    Test::More:      0
    version:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
